---
# tasks file for ansible-role-monit

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create monit.d directory
  file:
    path: "{{ monit_conf_include_dir }}"
    mode: 0755
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    state: directory
  notify: Restart monit

- name: Create monirc fragments
  template:
    src: monitrc.fragment.j2
    dest: "{{ monit_conf_include_dir }}/{{ item.key }}.monitrc"
    mode: 0600
  with_dict: "{{ monit_rc }}"


- name: Create monit.conf
  template:
    src: monitrc.j2
    dest: "{{ monit_conf_file }}"
    mode: 0600
    backup: yes
  register: register_monitrc
  notify: Restart monit

- shell: "find {{ monit_conf_dir }} -iname '{{ monit_conf_file }}.*@*~' -type f | sort | head -n 3 | xargs -r -n 1 rm"
  changed_when: false
  when: "{{ register_monitrc.changed }}"

- command: "monit -t -c {{ monit_conf_file }}"
  changed_when: false
  when: "{{ register_monitrc.changed }}"

- name: Create pre-defined script
  copy:
    dest: "{{ monit_script_path }}/{{ item }}"
    src: "{{ item }}"
    mode: 0755
  with_items: "{{ monit_scripts }}"

- name: Start monit
  service:
    name: "{{ monit_service }}"
    enabled: true
    state: started
