---
# tasks file for ansible-role-monit

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create monit.d directory
  file:
    path: "{{ monit_conf_include_dir }}"
    mode: 0755
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    state: directory
  notify: Restart monit

- name: Create monirc fragments
  template:
    src: monitrc.fragment.j2
    dest: "{{ monit_conf_include_dir }}/{{ item.key }}.monitrc"
    mode: 0600
  with_dict: "{{ monit_rc }}"


- name: Create monit.conf
  template:
    src: monitrc.j2
    dest: "{{ monit_conf_file }}"
    mode: 0600
    validate: "monit -t -c %s"
  notify: Restart monit

- name: Start monit
  service:
    name: "{{ monit_service }}"
    enabled: true
    state: started
